import { ChangeSet, ContextSelection, HealthScore, ReviewFinding, ValidationIssue, ValidationResult } from "./models";
import { CommitPolicy, SubjectCase } from "./policy";

const CONVENTIONAL = /^(?<type>[a-z][a-z0-9-]*)(?:\((?<scope>[^)\r\n]+)\))?(?<breaking>!)?: (?<subject>\S.*)$/;
const FORBIDDEN = [/^here(?:'s| is) (?:the )?commit message/i, /^commit message:/i, /generated by (?:ai|gitmind)/i, /as an ai/i];
const TRAILER = /^(?<name>[A-Za-z][A-Za-z-]*)(?:: | #).+$/;

function matchesCase(value: string, style: SubjectCase): boolean {
  const words = value.replace(/[^\p{L}\p{N}]+/gu, " ").trim().split(/\s+/);
  if (!words[0]) {return true;}
  switch (style) {
    case "lower-case": return value === value.toLocaleLowerCase();
    case "upper-case": return value === value.toLocaleUpperCase();
    case "sentence-case": return /^\p{Lu}/u.test(words[0]);
    case "start-case": return words.every(word => /^\p{Lu}/u.test(word));
    case "pascal-case": return !/[^\p{L}\p{N}]/u.test(value) && /^\p{Lu}/u.test(value);
    case "kebab-case": return /^[\p{Ll}\p{N}]+(?:-[\p{Ll}\p{N}]+)*$/u.test(value);
  }
}

export function validateCandidate(message: string, policy: CommitPolicy, options: { conventional?: boolean; changedFiles?: string[] } = {}): ValidationResult {
  const normalized = message
    .replace(/\r\n/g, "\n")
    .replace(/^([a-z0-9-]+(?:\([^)]+\))?!?)(?:\s*:){2,}/gim, "$1:")
    .trim();
  const issues: ValidationIssue[] = [];
  if (!normalized) {return { valid: false, normalized, issues: [{ code: "empty", message: "The provider returned an empty message", severity: "error" }] };}
  if (/\t| +$/m.test(normalized)) {issues.push({ code: "whitespace", message: "Message contains tabs or trailing whitespace", severity: "error" });}
  const lines = normalized.split("\n");
  if (lines.length > 1 && lines[1] !== "") {issues.push({ code: "separator", message: "Subject and body must be separated by a blank line", severity: "error", line: 2 });}
  const header = lines[0];
  const max = policy.subjectMaxLength ?? 72;
  if (header.length > max) {issues.push({ code: "header-length", message: `Subject exceeds ${max} characters`, severity: "error", line: 1 });}
  FORBIDDEN.forEach(pattern => { if (pattern.test(normalized)) {issues.push({ code: "boilerplate", message: "Message contains forbidden AI boilerplate or attribution", severity: "error" });} });
  const conventional = CONVENTIONAL.exec(header);
  if (options.conventional || policy.allowedTypes || policy.allowedScopes || policy.scopeRequired) {
    if (!conventional?.groups) {issues.push({ code: "structure", message: "Subject does not match Conventional Commits structure", severity: "error", line: 1 });}
    else {
      if (policy.allowedTypes && !policy.allowedTypes.includes(conventional.groups.type)) {issues.push({ code: "type", message: `Type '${conventional.groups.type}' is not allowed`, severity: "error", line: 1 });}
      if (policy.scopeRequired && !conventional.groups.scope) {issues.push({ code: "scope-required", message: "A scope is required", severity: "error", line: 1 });}
      if (conventional.groups.scope && policy.allowedScopes && !policy.allowedScopes.includes(conventional.groups.scope)) {issues.push({ code: "scope", message: `Scope '${conventional.groups.scope}' is not allowed`, severity: "error", line: 1 });}
      const cases = Array.isArray(policy.subjectCase) ? policy.subjectCase : policy.subjectCase ? [policy.subjectCase] : [];
      if (cases.length && !cases.some(style => matchesCase(conventional.groups?.subject ?? "", style))) {issues.push({ code: "subject-case", message: `Subject must use ${cases.join(" or ")}`, severity: "error", line: 1 });}
    }
  }
  if (policy.bodyMaxLines !== undefined && Math.max(0, lines.length - 2) > policy.bodyMaxLines) {issues.push({ code: "body-lines", message: `Body exceeds ${policy.bodyMaxLines} lines`, severity: "error" });}
  lines.slice(2).forEach((line, index) => {
    const trailer = TRAILER.exec(line);
    if (trailer?.groups) {
      const name = trailer.groups.name.toLowerCase();
      if (policy.deniedTrailers?.some(value => value.toLowerCase() === name) || (policy.allowedTrailers && !policy.allowedTrailers.some(value => value.toLowerCase() === name))) {issues.push({ code: "trailer", message: `Trailer '${trailer.groups.name}' is not allowed`, severity: "error", line: index + 3 });}
      if ((policy.footerMaxLineLength ?? Infinity) < line.length) {issues.push({ code: "footer-length", message: "Footer line is too long", severity: "error", line: index + 3 });}
    } else if ((policy.bodyMaxLineLength ?? Infinity) < line.length) {issues.push({ code: "body-length", message: "Body line is too long", severity: "error", line: index + 3 });}
  });
  if (policy.ticketRequired && policy.ticketPattern && !new RegExp(policy.ticketPattern).test(normalized)) {issues.push({ code: "ticket", message: "A repository ticket reference is required", severity: "error" });}
  if (options.changedFiles && options.changedFiles.length > 1) {
    const listed = options.changedFiles.filter(file => normalized.includes(file));
    if (listed.length >= Math.ceil(options.changedFiles.length * 0.75)) {issues.push({ code: "file-list", message: "Body repeats a file inventory instead of explaining intent", severity: "error" });}
  }
  return { valid: !issues.some(issue => issue.severity === "error"), issues, normalized };
}

export function shouldIncludeBody(mode: "auto" | "concise" | "detailed", changeSet: ChangeSet, selection: ContextSelection): boolean {
  if (mode === "detailed") {return true;}
  if (mode === "concise") {return false;}
  const selected = new Set(selection.items.filter(item => item.decision !== "excluded").map(item => item.atomId));
  const atoms = changeSet.atoms.filter(atom => selected.has(atom.id));
  return Boolean(selection.why?.trim()) || atoms.some(atom => /BREAKING CHANGE|breaking/i.test(atom.patch)) || new Set(atoms.map(atom => atom.path)).size > 2 || atoms.length > 3;
}

function clamp(value: number): number { return Math.max(0, Math.min(100, Math.round(value))); }

/**
 * Deterministic, local hygiene score for staged changes. It deliberately never
 * receives a generated commit message: health describes the change set, not
 * the wording chosen by a provider.
 */
export function scoreCommitHealth(changeSet: ChangeSet, selection?: ContextSelection): HealthScore {
  const decisions = new Map(selection?.items.map(item => [item.atomId, item.decision]) ?? []);
  const staged = changeSet.atoms.filter(atom => atom.origin === "staged" && (decisions.size === 0 || decisions.get(atom.id) !== "excluded"));
  const roots = new Set(staged.map(atom => atom.path.split("/")[0]));
  const files = new Set(staged.map(atom => atom.path));
  const changedLines = staged.reduce((total, atom) => total + atom.additions + atom.deletions, 0);
  const secretFindings = staged.reduce((total, atom) => total + (/(?:private[_-]?key|api[_-]?key|secret|password)\s*[=:]/i.test(atom.patch) || /-----BEGIN [A-Z ]*PRIVATE KEY-----/.test(atom.patch) ? 1 : 0), 0);
  const debugFindings = staged.reduce((total, atom) => total + ((atom.patch.match(/^\+.*(?:console\.log\(|debugger\b)/gm) ?? []).length), 0);
  const scope = clamp(100 - Math.max(0, roots.size - 1) * 16 - Math.max(0, files.size - 10) * 3);
  const changeSize = clamp(100 - Math.max(0, changedLines - 250) / 12 - Math.max(0, changedLines - 1000) / 8);
  const safety = clamp(100 - secretFindings * 55 - debugFindings * 12);
  // A diff alone cannot prove that a source change needs a test. Treating a
  // missing test-file change as a failure produced noisy false positives, so
  // Health reports test activity when present but never guesses coverage.
  const testCoverage = 100;
  const staging = staged.length ? 100 : 0;
  const subscores = { scope, changeSize, safety, testCoverage, staging };
  const recommendations: string[] = [];
  if (!staged.length) {recommendations.push("Stage the changes you want to assess before committing.");}
  if (scope < 80) {recommendations.push("Consider splitting unrelated areas into smaller commits.");}
  if (changeSize < 80) {recommendations.push("Consider splitting this large change into reviewable pieces.");}
  if (safety < 100) {recommendations.push("Remove credentials and temporary debug statements before committing.");}
  if (!recommendations.length) {recommendations.push("The staged change set is focused and ready for review.");}
  return {
    overall: clamp(scope * .25 + changeSize * .20 + safety * .35 + testCoverage * .15 + staging * .05),
    subscores,
    explanations: {
      scope: "Number of files and top-level areas touched",
      changeSize: "Changed lines kept within a reviewable range",
      safety: "Potential credentials and added debug statements",
      testCoverage: "Test changes are informative, but coverage is not inferred from a diff",
      staging: "Only staged changes are eligible for this score"
    },
    recommendations
  };
}

export function validateReviewFindings(findings: readonly ReviewFinding[], knownAtomIds: readonly string[]): ReviewFinding[] {
  const known = new Set(knownAtomIds);
  return (findings ?? [])
    .filter(finding => finding && typeof finding.title === "string" && ["info", "warning", "error"].includes(finding.severity))
    .filter(finding => !Array.isArray(finding.atomIds) || finding.atomIds.length === 0 || finding.atomIds.some(id => known.has(id)))
    .map(finding => {
      const validAtomIds = Array.isArray(finding.atomIds) ? finding.atomIds.filter(id => known.has(id)) : [];
      return {
        ...finding,
        atomIds: validAtomIds.length > 0 ? validAtomIds : knownAtomIds.slice()
      };
    });
}

export function reviewBlocks(findings: readonly ReviewFinding[], threshold: CommitPolicy["reviewBlockingThreshold"]): boolean {
  if (!threshold || threshold === "off") {return false;}
  const rank = { info: 0, warning: 1, error: 2 };
  return findings.some(finding => rank[finding.severity] >= rank[threshold]);
}
