import { ChangeSet, ContextSelection, HealthScore, ReviewFinding, ValidationIssue, ValidationResult } from "./models";
import { CommitPolicy, SubjectCase } from "./policy";

const CONVENTIONAL = /^(?<type>[a-z][a-z0-9-]*)(?:\((?<scope>[^)\r\n]+)\))?(?<breaking>!)?: (?<subject>\S.*)$/;
const FORBIDDEN = [/^here(?:'s| is) (?:the )?commit message/i, /^commit message:/i, /generated by (?:ai|gitmind)/i, /as an ai/i];
const TRAILER = /^(?<name>[A-Za-z][A-Za-z-]*)(?:: | #).+$/;

function matchesCase(value: string, style: SubjectCase): boolean {
  const words = value.replace(/[^\p{L}\p{N}]+/gu, " ").trim().split(/\s+/);
  if (!words[0]) {return true;}
  switch (style) {
    case "lower-case": return value === value.toLocaleLowerCase();
    case "upper-case": return value === value.toLocaleUpperCase();
    case "sentence-case": return /^\p{Lu}/u.test(words[0]);
    case "start-case": return words.every(word => /^\p{Lu}/u.test(word));
    case "pascal-case": return !/[^\p{L}\p{N}]/u.test(value) && /^\p{Lu}/u.test(value);
    case "kebab-case": return /^[\p{Ll}\p{N}]+(?:-[\p{Ll}\p{N}]+)*$/u.test(value);
  }
}

export function validateCandidate(message: string, policy: CommitPolicy, options: { conventional?: boolean; changedFiles?: string[] } = {}): ValidationResult {
  const normalized = message
    .replace(/\r\n/g, "\n")
    .replace(/^([a-z0-9-]+(?:\([^)]+\))?!?)(?:\s*:){2,}/gim, "$1:")
    .trim();
  const issues: ValidationIssue[] = [];
  if (!normalized) {return { valid: false, normalized, issues: [{ code: "empty", message: "The provider returned an empty message", severity: "error" }] };}
  if (/\t| +$/m.test(normalized)) {issues.push({ code: "whitespace", message: "Message contains tabs or trailing whitespace", severity: "error" });}
  const lines = normalized.split("\n");
  if (lines.length > 1 && lines[1] !== "") {issues.push({ code: "separator", message: "Subject and body must be separated by a blank line", severity: "error", line: 2 });}
  const header = lines[0];
  const max = policy.subjectMaxLength ?? 72;
  if (header.length > max) {issues.push({ code: "header-length", message: `Subject exceeds ${max} characters`, severity: "error", line: 1 });}
  FORBIDDEN.forEach(pattern => { if (pattern.test(normalized)) {issues.push({ code: "boilerplate", message: "Message contains forbidden AI boilerplate or attribution", severity: "error" });} });
  const conventional = CONVENTIONAL.exec(header);
  if (options.conventional || policy.allowedTypes || policy.allowedScopes || policy.scopeRequired) {
    if (!conventional?.groups) {issues.push({ code: "structure", message: "Subject does not match Conventional Commits structure", severity: "error", line: 1 });}
    else {
      if (policy.allowedTypes && !policy.allowedTypes.includes(conventional.groups.type)) {issues.push({ code: "type", message: `Type '${conventional.groups.type}' is not allowed`, severity: "error", line: 1 });}
      if (policy.scopeRequired && !conventional.groups.scope) {issues.push({ code: "scope-required", message: "A scope is required", severity: "error", line: 1 });}
      if (conventional.groups.scope && policy.allowedScopes && !policy.allowedScopes.includes(conventional.groups.scope)) {issues.push({ code: "scope", message: `Scope '${conventional.groups.scope}' is not allowed`, severity: "error", line: 1 });}
      const cases = Array.isArray(policy.subjectCase) ? policy.subjectCase : policy.subjectCase ? [policy.subjectCase] : [];
      if (cases.length && !cases.some(style => matchesCase(conventional.groups?.subject ?? "", style))) {issues.push({ code: "subject-case", message: `Subject must use ${cases.join(" or ")}`, severity: "error", line: 1 });}
    }
  }
  if (policy.bodyMaxLines !== undefined && Math.max(0, lines.length - 2) > policy.bodyMaxLines) {issues.push({ code: "body-lines", message: `Body exceeds ${policy.bodyMaxLines} lines`, severity: "error" });}
  lines.slice(2).forEach((line, index) => {
    const trailer = TRAILER.exec(line);
    if (trailer?.groups) {
      const name = trailer.groups.name.toLowerCase();
      if (policy.deniedTrailers?.some(value => value.toLowerCase() === name) || (policy.allowedTrailers && !policy.allowedTrailers.some(value => value.toLowerCase() === name))) {issues.push({ code: "trailer", message: `Trailer '${trailer.groups.name}' is not allowed`, severity: "error", line: index + 3 });}
      if ((policy.footerMaxLineLength ?? Infinity) < line.length) {issues.push({ code: "footer-length", message: "Footer line is too long", severity: "error", line: index + 3 });}
    } else if ((policy.bodyMaxLineLength ?? Infinity) < line.length) {issues.push({ code: "body-length", message: "Body line is too long", severity: "error", line: index + 3 });}
  });
  if (policy.ticketRequired && policy.ticketPattern && !new RegExp(policy.ticketPattern).test(normalized)) {issues.push({ code: "ticket", message: "A repository ticket reference is required", severity: "error" });}
  if (options.changedFiles && options.changedFiles.length > 1) {
    const listed = options.changedFiles.filter(file => normalized.includes(file));
    if (listed.length >= Math.ceil(options.changedFiles.length * 0.75)) {issues.push({ code: "file-list", message: "Body repeats a file inventory instead of explaining intent", severity: "error" });}
  }
  return { valid: !issues.some(issue => issue.severity === "error"), issues, normalized };
}

export function shouldIncludeBody(mode: "auto" | "concise" | "detailed", changeSet: ChangeSet, selection: ContextSelection): boolean {
  if (mode === "detailed") {return true;}
  if (mode === "concise") {return false;}
  const selected = new Set(selection.items.filter(item => item.decision !== "excluded").map(item => item.atomId));
  const atoms = changeSet.atoms.filter(atom => selected.has(atom.id));
  return Boolean(selection.why?.trim()) || atoms.some(atom => /BREAKING CHANGE|breaking/i.test(atom.patch)) || new Set(atoms.map(atom => atom.path)).size > 2 || atoms.length > 3;
}

function clamp(value: number): number { return Math.max(0, Math.min(100, Math.round(value))); }

export function scoreCommitHealth(message: string, validation: ValidationResult, changeSet: ChangeSet, selection: ContextSelection): HealthScore {
  const selected = changeSet.atoms.filter(atom => selection.items.some(item => item.atomId === atom.id && item.decision !== "excluded"));
  const subject = message.split("\n")[0] ?? "";
  const words = new Set(subject.toLowerCase().match(/[a-z0-9]{3,}/g) ?? []);
  const pathWords = new Set(selected.flatMap(atom => atom.path.toLowerCase().split(/[^a-z0-9]+/)).filter(word => word.length >= 3));
  const overlap = [...words].filter(word => pathWords.has(word)).length;
  const relevance = clamp(55 + overlap * 10 - (selected.length === 0 ? 55 : 0));
  const concernRoots = new Set(selected.map(atom => atom.path.split("/")[0]));
  const atomicity = clamp(100 - Math.max(0, concernRoots.size - 1) * 15 - Math.max(0, selected.length - 8) * 3);
  const ruleCompliance = clamp(100 - validation.issues.filter(issue => issue.severity === "error").length * 25 - validation.issues.filter(issue => issue.severity === "warning").length * 8);
  const intentCompleteness = clamp(selection.why ? (message.length > subject.length ? 100 : 70) : 60);
  const verbosity = clamp(subject.length <= 72 ? (message.length < 1200 ? 100 : 65) : 50);
  const subscores = { relevance, atomicity, ruleCompliance, intentCompleteness, verbosity };
  return { overall: clamp(relevance * .30 + atomicity * .25 + ruleCompliance * .25 + intentCompleteness * .10 + verbosity * .10), subscores,
    explanations: { relevance: "Subject terms compared with selected change paths", atomicity: "Breadth of selected files and top-level concerns", ruleCompliance: "Repository and style validation results", intentCompleteness: "Whether the draft explains supplied intent", verbosity: "Subject and body length balance" } };
}

export function validateReviewFindings(findings: readonly ReviewFinding[], knownAtomIds: readonly string[]): ReviewFinding[] {
  const known = new Set(knownAtomIds);
  return findings.filter(finding => finding.atomIds.length > 0 && finding.atomIds.every(id => known.has(id)) && ["info", "warning", "error"].includes(finding.severity));
}

export function reviewBlocks(findings: readonly ReviewFinding[], threshold: CommitPolicy["reviewBlockingThreshold"]): boolean {
  if (!threshold || threshold === "off") {return false;}
  const rank = { info: 0, warning: 1, error: 2 };
  return findings.some(finding => rank[finding.severity] >= rank[threshold]);
}

