// Order matches the artwork. IDs match GitMind's runtime catalog (azure uses azureopenai).
export const providers = [
  ["copilot", "GitHub Copilot", "Your editor subscription"],
  ["ollama", "Ollama", "Run models locally"],
  ["lmstudio", "LM Studio", "Run models locally"],
  ["openai", "OpenAI", "Cloud API"],
  ["anthropic", "Anthropic", "Cloud API"],
  ["gemini", "Google Gemini", "Cloud API"],
  ["deepseek", "DeepSeek", "Cloud API"],
  ["grok", "xAI Grok", "Cloud API"],
  ["groq", "Groq", "Cloud API"],
  ["perplexity", "Perplexity", "Cloud API"],
  ["zai", "Z.ai", "Cloud API"],
  ["mistral", "Mistral AI", "Cloud API"],
  ["cohere", "Cohere", "Cloud API"],
  ["huggingface", "Hugging Face", "Hosted models"],
  ["together", "Together AI", "Hosted models"],
  ["openrouter", "OpenRouter", "Model gateway"],
  ["minimax", "MiniMax", "Cloud API"],
  ["nvidia", "NVIDIA NIM", "Hosted models"],
  ["azure", "Azure OpenAI", "Cloud platform"],
  ["bedrock", "Amazon Bedrock", "Cloud platform"],
  ["vertexai", "Vertex AI", "Cloud platform"],
  ["cloudflare", "Cloudflare", "Workers AI / AI Gateway"],
];
